
name: Mine
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:


jobs:
  build:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
      statuses: write
      deployments: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install requests bs4 jsbeautifier PyGithub
    - name: Run script
      run: |
        python ./src/strings.py
      env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

